#!/bin/bash

usage()
{
    echo "Usage : $0 [options] -c \"command\""
    echo "Loads MemMap kernel module and configure it to monitor command, then
    execute the command given by the user"
    echo "-c cmd            The command to be executed"
    echo "Options:"
    echo "-w    interval    Set the wakeup interval for MemMap to interval ms,
    default: $interval"
    echo "-a \"args\"       The arguments for command"
    echo "-h                Display this help and exit"
    echo "-p prio           Schedtool priority for the kernel module, the user
    program priority will be prio-1, default: $prio"
    echo "-d dir            Path to the MemMap dir default $install_dir"
    echo "-f file           Log into file"
    echo "-n maxtasks       Set the maximum of tasks instrument, default 128"
    echo "-m                Pin thread manually. If you use this option, $0
                            will assume that you have pinned the thread (aka
                            each thread can run on only one proc). By default
                            $0 pin the threads automatically in a round robin
                            way by creation ordre"
}

which schedtool > /dev/null
if [ $? -ne 0 ]
then
    echo "$0 requires the schedtool which is not find in your PATH"
    echo "Please install schedtool or update your PATH"
    exit 1
fi

if [ $(whoami) != "root"  ]
then
    echo "$0 must be run as root"
    exit 1
fi

prio=$(schedtool -r | grep FIFO | sed -e 's/.*prio_max \([0-9]*\)/\1/')
install_dir="~/install/MemMap"

while getopts "w:c:a:hp:d:f:n:m" opt
do
    case $opt in
        h)
            usage
            exit 0
            ;;
        w)
            memmap_interval="MemMap_wakeupInterval=$OPTARG"
            ;;
        a)
            args="$OPTARG"
            ;;
        c)
            cmd="$OPTARG"
            ;;
        p)
            prio=$OPTARG
            ;;
        d)
            install_dir="$OPTARG"
            ;;
        f)
            logfile="$OPTARG"
            ;;
        n)
            memmap_maxprocess="MemMap_maxProcess=$OPTARG"
            ;;
        m)
            memmap_pin="MemMap_pinProc=0"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ -z "$cmd" ]
then
    echo "A command is required"
    usage
    exit 1
fi

# Wait for the kernel module to start
child()
{
    echo "Child $BASHPID waiting for a signal from my parent"
    kill -s SIGSTOP $BASHPID
    echo "Child $BASHPID awake"
    if [ -z "$logfile" ]
    then
        $cmd $args
    else
        $cmd $args > $logfile 2>&1
    fi
    ret=$?
    echo "$cmd ended code $ret"
    exit $ret
}

abort_on_error()
{
    if [ $1 -ne 0 ]
    then
        kill -9 $pid
        echo "Fatal error: $2"
        echo "aborting"
        exit 1
    fi
}

child &
pid=$!
let user_prio=$(( $prio - 1 ))
schedtool -F -p $user_prio $pid
schedtool -F -p $prio $$
cd $install_dir/src/module/
make clean && make
abort_on_error $? "make fail"
# make install
# abort_on_error $? "Install fail"
insmod memmap.ko MemMap_mainPid=$pid MemMap_schedulerPriority=$prio \
    $memmap_interval $memmap_maxprocess $memmap_pin
abort_on_error $? "unable to load module"
kill -s SIGCONT $pid
echo "Parent $BASHPID waiting for child $pid in script $$"
wait $pid
rmmod memmap
