#!/bin/bash

usage()
{
    echo "Usage : $name [options] -c \"command\""
    echo "Loads $name kernel module and configure it to monitor the user given
    command."
    echo "  -c cmd            The command to be monitored."
    echo "Options:"
    echo "  -h                Display this help and exit."
    echo "  -a \"args\"         The arguments for command."
    echo "  -d dir            Path to the Moca dir. Default: $install_dir"
    echo "  -f file           Log cmd into file. Default: Moca-cmd.log"
    echo "  -l file           Log module output into file. Default: cmd-date"
    echo "  -n                Do not compile the module"
    echo "  -D dirname        Set the output directory. Default: $logdir"
    echo -e "\n  The following parameters allows you to do fine tuning on the
    module. By default you shouldn't need to use them.
    + If you encounter performance issues, you can increase the wakeup
    interval, the priority (reduce the system noise) or the hashmap numbit
    parameter.
    + If $name tells you that a part of the trace have been dropped because
    there was not enought space to sotre it, you can increase the number of
    chunks, the chunksize or reduce the wakeup interval.
    Please note that, as memory is quite restricted in the kernel, it might be a
    better idea to play on the wakeup interval the priority than on the storage
    related parameters.\n"
    echo "  -w ms             Set the wakeup interval for Moca to interval ms,
    Default: 50ms"
    echo "  -p prio           Schedtool priority for the kernel module, the program
    priority will be prio-1. You can increase this parameter
    to reduce the system noise. Default: $prio"
    echo "  -b numbits        Set the number of bits used for the chunk hashmaps.
    The map size is 2^numbits. the higher numbits is, the
    less collision you should have. Default: 14"
    echo "  -S ChunkSize      Set the number of adress that can be stored in one
    chunk. You can also reduce the wakeup interval, and
    therefore the number of adresses needed per chunks.
    Default: 2*2^14."
    echo "  -C nbChunks       Set the number of chunks kept in memory. Default: 20."
}

install_dir="~/install/Moca"
kernLogFile="Moca"
procdir="/proc/Moca"
log_thread_interval=.5
Moca_log="Moca-output.log"
name=$(basename $0)
compi=true

while getopts "c:ha:d:f:l:w:p:b:S:C:D:n" opt
do
    case $opt in
        c)
            cmd="$OPTARG"
            ;;
        h)
            usage
            exit 0
            ;;
        a)
            args="$OPTARG"
            ;;
        d)
            install_dir="$OPTARG"
            ;;
        D)
            logdir="$OPTARG"
            ;;
        f)
            logfile="$OPTARG"
            ;;
        l)
            Moca_log="$OPTARG"
            ;;
        w)
            moca_interval="Moca_wakeupInterval=$OPTARG"
            ;;
        p)
            prio=$OPTARG
            moca_prio="Moca_schedulerPriority=$OPTARG"
            which schedtool > /dev/null
            if [ $? -ne 0 ]
            then
                echo "$0 requires the schedtool to set the priority."
                echo "Please install schedtool or update your PATH"
                exit 1
            fi
            ;;
        b)
            moca_bits="Moca_taskDataHashBits=$OPTARG"
            ;;
        S)
            moca_factor="Moca_taskDataChunkSize=$OPTARG"
            ;;
        C)
            moca_chunks="Moca_nbChunks=$OPTARG"
            ;;
        n)
            compi=false;
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ $(whoami) != "root"  ]
then
    echo "$0 must be run as root"
    exit 1
fi

if [ -z "$cmd" ]
then
    echo "A command is required"
    usage
    exit 1
fi
program=$(basename $cmd)

if [ -z "$logdir" ]
then
    logdir="Moca-$program-$(date +%Y-%m-%d_%H-%M-%S)"
fi
mkdir $logdir

if [ -z "$logfile" ]
then
    logfile="$logdir/Moca-$program.log"
fi
kernLogFile="$logdir/$kernLogFile"

# Wait for the kernel module to start
child()
{
    #echo "Child $BASHPID waiting for a signal from my parent"
    kill -s SIGSTOP $BASHPID
    #echo "Child $BASHPID awake"
    if [ -z "$logfile" ]
    then
        $cmd $args
    else
        $cmd $args > $logfile 2> $logfile.err
    fi
    ret=$?
    echo "$cmd ended code $ret"
    exit $ret
}
log()
{
    while test -e $procdir
    do
        for f in $(\ls $procdir)
        do
            cat $procdir/$f >> $kernLogFile-$f.log
        done
        sleep $log_thread_interval
    done
}

abort_on_error()
{
    if [ $1 -ne 0 ]
    then
        kill -9 $pid
        echo "Fatal error: $2"
        echo "aborting"
        exit 1
    fi
}
child &
pid=$!

if [ ! -z $prio ]
then
    let user_prio=$(( $prio - 1 ))
    schedtool -F -p $prio $$
    schedtool -F -p $user_prio $pid
fi
cd $install_dir/src/module/
if $compi
then
    make clean && make
    abort_on_error $? "make fail"
fi
# make install
# abort_on_error $? "Install fail"
insmod moca.ko Moca_mainPid=$pid $moca_interval $moca_bits $moca_factor \
    $moca_chunks $moca_prio
abort_on_error $? "unable to load module"
cd -
log &
logpid=$!
if [ ! -z $prio ]
then
    schedtool -F -p $prio $logpid
fi
kill -s SIGCONT $pid
#echo "Parent $BASHPID waiting for child $pid in script $$"
wait $pid
rmmod moca
# Create the log
line=$(grep -n "Moca started" /var/log/kern.log | tail -n 1 | cut -d ':' -f 1)
line=$(($line-1))
line+='d'
sed 1,$line /var/log/kern.log | grep -i "moca" > $logdir/$Moca_log
# Create the event poducers log (required by framesoc)
fields=('2' '3')
fieldsName=('Physical' 'Virtual')
pgsize=$(head -n 1 $kernLogFile-task0.log  | cut -d ' ' -f 4)
cd $logdir
for i in ${!fields[*]}
do
    f=${fields[$i]}
    name=${fieldsName[$i]}
    grep "Access" -RH | cut -d ' ' -f 1,$f | \
        sed -e 's/.*Moca-\([^\.]*\).log/\1/' -e 's/:Access//' \
        -e 's/\([^ ]*\) \(.*\)/\2 \1/' | sort | uniq | \
        awk '{if(ADD==$1) {ACC=ACC" "$2} else {print ADD,ACC;ADD=$1;ACC=$2}} END {print ADD ACC }' \
        > Moca-$name.log
    sed -i "1 s/\(.*\)/$pgsize\n\1/" Moca-$name.log
done
cd -
